-- spaced_learning.books definition

-- Drop table

-- DROP TABLE spaced_learning.books;

CREATE TABLE spaced_learning.books (
                                       id uuid NOT NULL,
                                       "name" varchar(100) NOT NULL,
                                       status varchar(20) NULL DEFAULT 'DRAFT'::character varying,
                                       difficulty_level varchar(20) NULL,
                                       category varchar(50) NULL,
                                       description text NULL,
                                       book_no int4 NULL DEFAULT 0,
                                       created_at timestamp(6) NULL,
                                       updated_at timestamp(6) NULL,
                                       deleted_at timestamp(6) NULL,
                                       CONSTRAINT books_difficulty_level_check CHECK (((difficulty_level)::text = ANY (ARRAY[('BEGINNER'::character varying)::text, ('INTERMEDIATE'::character varying)::text, ('ADVANCED'::character varying)::text, ('EXPERT'::character varying)::text]))),
	CONSTRAINT books_pkey PRIMARY KEY (id),
	CONSTRAINT books_status_check CHECK (((status)::text = ANY (ARRAY[('PUBLISHED'::character varying)::text, ('DRAFT'::character varying)::text, ('ARCHIVED'::character varying)::text])))
);
CREATE INDEX idx_books_category ON spaced_learning.books USING btree (category);
CREATE INDEX idx_books_difficulty_level ON spaced_learning.books USING btree (difficulty_level);
CREATE INDEX idx_books_status ON spaced_learning.books USING btree (status);


-- spaced_learning.roles definition

-- Drop table

-- DROP TABLE spaced_learning.roles;

CREATE TABLE spaced_learning.roles (
                                       id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       "name" varchar(50) NOT NULL,
                                       description varchar(255) NULL,
                                       CONSTRAINT roles_pkey PRIMARY KEY (id),
                                       CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);


-- spaced_learning.users definition

-- Drop table

-- DROP TABLE spaced_learning.users;

CREATE TABLE spaced_learning.users (
                                       id uuid NOT NULL,
                                       username varchar(50) NOT NULL,
                                       email varchar(100) NOT NULL,
                                       "password" varchar(120) NOT NULL,
                                       "name" varchar(100) NOT NULL,
                                       status varchar(20) NULL DEFAULT 'ACTIVE'::character varying,
                                       last_active_date timestamp(6) NULL,
                                       created_at timestamp(6) NULL,
                                       updated_at timestamp(6) NULL,
                                       deleted_at timestamp(6) NULL,
                                       CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                                       CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username),
                                       CONSTRAINT users_pkey PRIMARY KEY (id),
                                       CONSTRAINT users_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('SUSPENDED'::character varying)::text])))
);
CREATE INDEX idx_users_email ON spaced_learning.users USING btree (email);
CREATE INDEX idx_users_status ON spaced_learning.users USING btree (status);
CREATE INDEX idx_users_username ON spaced_learning.users USING btree (username);


-- spaced_learning.modules definition

-- Drop table

-- DROP TABLE spaced_learning.modules;

CREATE TABLE spaced_learning.modules (
                                         id uuid NOT NULL,
                                         book_id uuid NOT NULL,
                                         module_no int4 NOT NULL,
                                         title varchar(255) NOT NULL,
                                         word_count int4 NULL DEFAULT 0,
                                         created_at timestamp(6) NULL,
                                         updated_at timestamp(6) NULL,
                                         deleted_at timestamp(6) NULL,
                                         url varchar(500) NULL,
                                         CONSTRAINT modules_module_no_check CHECK ((module_no >= 1)),
                                         CONSTRAINT modules_pkey PRIMARY KEY (id),
                                         CONSTRAINT modules_word_count_check CHECK ((word_count >= 0)),
                                         CONSTRAINT fkh6s7r2n5vtsmg4xjhao3818t FOREIGN KEY (book_id) REFERENCES spaced_learning.books(id)
);
CREATE INDEX idx_modules_book_id ON spaced_learning.modules USING btree (book_id);


-- spaced_learning.user_books definition

-- Drop table

-- DROP TABLE spaced_learning.user_books;

CREATE TABLE spaced_learning.user_books (
                                            user_id uuid NOT NULL,
                                            book_id uuid NOT NULL,
                                            created_at timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP,
                                            CONSTRAINT user_books_pkey PRIMARY KEY (user_id, book_id),
                                            CONSTRAINT fk_user_books_book FOREIGN KEY (book_id) REFERENCES spaced_learning.books(id),
                                            CONSTRAINT fk_user_books_user FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id)
);
CREATE INDEX idx_user_books_book_id ON spaced_learning.user_books USING btree (book_id);
CREATE INDEX idx_user_books_user_id ON spaced_learning.user_books USING btree (user_id);


-- spaced_learning.user_roles definition

-- Drop table

-- DROP TABLE spaced_learning.user_roles;

CREATE TABLE spaced_learning.user_roles (
                                            user_id uuid NOT NULL,
                                            role_id int8 NOT NULL,
                                            CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
                                            CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES spaced_learning.roles(id),
                                            CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id)
);


-- spaced_learning.user_statistics definition

-- Drop table

-- DROP TABLE spaced_learning.user_statistics;

CREATE TABLE spaced_learning.user_statistics (
                                                 id uuid NOT NULL,
                                                 user_id uuid NOT NULL,
                                                 streak_days int4 NULL DEFAULT 0,
                                                 streak_weeks int4 NULL DEFAULT 0,
                                                 longest_streak_days int4 NULL DEFAULT 0,
                                                 total_completed_modules int4 NULL DEFAULT 0,
                                                 total_in_progress_modules int4 NULL DEFAULT 0,
                                                 total_words int4 NULL DEFAULT 0,
                                                 learned_words int4 NULL DEFAULT 0,
                                                 vocabulary_completion_rate numeric(5, 2) NULL DEFAULT 0.00,
                                                 weekly_new_words_rate numeric(5, 2) NULL DEFAULT 0.00,
                                                 last_statistics_update timestamp(6) NULL,
                                                 created_at timestamp(6) NULL,
                                                 updated_at timestamp(6) NULL,
                                                 deleted_at timestamp(6) NULL,
                                                 CONSTRAINT user_statistics_pkey PRIMARY KEY (id),
                                                 CONSTRAINT fk_user_statistics_user FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id)
);
CREATE INDEX idx_user_statistics_user_id ON spaced_learning.user_statistics USING btree (user_id);
CREATE INDEX idx_user_stats_user ON spaced_learning.user_statistics USING btree (user_id);


-- spaced_learning.vocabularies definition

-- Drop table

-- DROP TABLE spaced_learning.vocabularies;

CREATE TABLE spaced_learning.vocabularies (
                                              id uuid NOT NULL,
                                              created_at timestamp(6) NULL,
                                              deleted_at timestamp(6) NULL,
                                              updated_at timestamp(6) NULL,
                                              definition text NULL,
                                              example text NULL,
                                              part_of_speech varchar(100) NOT NULL,
                                              pronunciation varchar(100) NULL,
                                              term varchar(100) NOT NULL,
                                              module_id uuid NOT NULL,
                                              CONSTRAINT vocabularies_pkey PRIMARY KEY (id),
                                              CONSTRAINT fk8jv5w637d8osy1xskp9daeib0 FOREIGN KEY (module_id) REFERENCES spaced_learning.modules(id)
);


-- spaced_learning.grammars definition

-- Drop table

-- DROP TABLE spaced_learning.grammars;

CREATE TABLE spaced_learning.grammars (
                                          id uuid NOT NULL,
                                          created_at timestamp(6) NULL,
                                          deleted_at timestamp(6) NULL,
                                          updated_at timestamp(6) NULL,
                                          example text NULL,
                                          explanation text NULL,
                                          title varchar(100) NOT NULL,
                                          usage_note text NULL,
                                          module_id uuid NOT NULL,
                                          CONSTRAINT grammars_pkey PRIMARY KEY (id),
                                          CONSTRAINT fkjbnujjgfwffjg1e1g7w30428u FOREIGN KEY (module_id) REFERENCES spaced_learning.modules(id)
);


-- spaced_learning.module_progress definition

-- Drop table

-- DROP TABLE spaced_learning.module_progress;

CREATE TABLE spaced_learning.module_progress (
                                                 id uuid NOT NULL,
                                                 module_id uuid NOT NULL,
                                                 cycles_studied varchar(30) NULL DEFAULT 'FIRST_TIME'::character varying,
                                                 first_learning_date date NULL,
                                                 next_study_date date NULL,
                                                 percent_complete numeric(5, 2) NULL DEFAULT 0.00,
                                                 created_at timestamp(6) NULL,
                                                 updated_at timestamp(6) NULL,
                                                 deleted_at timestamp(6) NULL,
                                                 extended_review_count int4 NULL DEFAULT 0,
                                                 CONSTRAINT module_progress_cycles_studied_check CHECK (((cycles_studied)::text = ANY (ARRAY[('FIRST_TIME'::character varying)::text, ('FIRST_REVIEW'::character varying)::text, ('SECOND_REVIEW'::character varying)::text, ('THIRD_REVIEW'::character varying)::text, ('MORE_THAN_THREE_REVIEWS'::character varying)::text]))),
	CONSTRAINT module_progress_pkey PRIMARY KEY (id),
	CONSTRAINT fkiwivm59wd0328gij7gayrr37 FOREIGN KEY (module_id) REFERENCES spaced_learning.modules(id)
);
CREATE INDEX idx_module_progress_module_id ON spaced_learning.module_progress USING btree (module_id);


-- spaced_learning.repetitions definition

-- Drop table

-- DROP TABLE spaced_learning.repetitions;

CREATE TABLE spaced_learning.repetitions (
                                             id uuid NOT NULL,
                                             module_progress_id uuid NOT NULL,
                                             repetition_order varchar(20) NOT NULL,
                                             status varchar(50) NULL DEFAULT 'NOT_STARTED'::character varying,
                                             review_date date NULL,
                                             created_at timestamp(6) NULL,
                                             updated_at timestamp(6) NULL,
                                             deleted_at timestamp(6) NULL,
                                             CONSTRAINT repetitions_pkey PRIMARY KEY (id),
                                             CONSTRAINT repetitions_repetition_order_check CHECK (((repetition_order)::text = ANY (ARRAY[('FIRST_REPETITION'::character varying)::text, ('SECOND_REPETITION'::character varying)::text, ('THIRD_REPETITION'::character varying)::text, ('FOURTH_REPETITION'::character varying)::text, ('FIFTH_REPETITION'::character varying)::text]))),
	CONSTRAINT repetitions_status_check CHECK (((status)::text = ANY (ARRAY[('NOT_STARTED'::character varying)::text, ('COMPLETED'::character varying)::text, ('SKIPPED'::character varying)::text]))),
	CONSTRAINT fk9lj2refs205nnsscajx9tywsk FOREIGN KEY (module_progress_id) REFERENCES spaced_learning.module_progress(id)
);
CREATE INDEX idx_repetitions_module_progress_id ON spaced_learning.repetitions USING btree (module_progress_id);
CREATE INDEX idx_repetitions_review_date ON spaced_learning.repetitions USING btree (review_date);
CREATE INDEX idx_repetitions_status ON spaced_learning.repetitions USING btree (status);


-- spaced_learning.learning_cycles definition

-- Drop table

-- DROP TABLE spaced_learning.learning_cycles;

CREATE TABLE spaced_learning.learning_cycles (
                                                 id uuid NOT NULL,
                                                 module_progress_id uuid NOT NULL,
                                                 cycles_studied varchar(30) NOT NULL,
                                                 start_date date NOT NULL,
                                                 description varchar(255) NULL,
                                                 created_at timestamp(6) NULL,
                                                 updated_at timestamp(6) NULL,
                                                 deleted_at timestamp(6) NULL,
                                                 CONSTRAINT learning_cycles_pkey PRIMARY KEY (id),
                                                 CONSTRAINT uk_learning_cycles_progress_cycle_date UNIQUE (module_progress_id, cycles_studied, start_date),
                                                 CONSTRAINT ukfsksm8mohbjitmamutub147cp UNIQUE (module_progress_id, cycles_studied, start_date),
                                                 CONSTRAINT fk_learning_cycles_module_progress FOREIGN KEY (module_progress_id) REFERENCES spaced_learning.module_progress(id)
);
CREATE INDEX idx_learning_cycles_cycle ON spaced_learning.learning_cycles USING btree (cycles_studied);
CREATE INDEX idx_learning_cycles_progress_id ON spaced_learning.learning_cycles USING btree (module_progress_id);
CREATE INDEX idx_learning_cycles_start_date ON spaced_learning.learning_cycles USING btree (start_date);