-- spaced_learning.books definition

-- Drop table

-- DROP TABLE spaced_learning.books;

CREATE TABLE spaced_learning.books (
	id uuid NOT NULL,
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	category varchar(50) NULL,
	description text NULL,
	difficulty_level varchar(20) NULL,
	"name" varchar(100) NOT NULL,
	status varchar(20) NULL,
	book_no int4 NULL,
	CONSTRAINT books_difficulty_level_check CHECK (((difficulty_level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[]))),
	CONSTRAINT books_pkey PRIMARY KEY (id),
	CONSTRAINT books_status_check CHECK (((status)::text = ANY ((ARRAY['PUBLISHED'::character varying, 'DRAFT'::character varying, 'ARCHIVED'::character varying])::text[])))
);


-- spaced_learning.roles definition

-- Drop table

-- DROP TABLE spaced_learning.roles;

CREATE TABLE spaced_learning.roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id),
	CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);


-- spaced_learning.users definition

-- Drop table

-- DROP TABLE spaced_learning.users;

CREATE TABLE spaced_learning.users (
	id uuid NOT NULL,
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	email varchar(100) NOT NULL,
	"name" varchar(100) NOT NULL,
	"password" varchar(120) NOT NULL,
	status varchar(20) NULL,
	last_active_date timestamp(6) NULL,
	username varchar(50) NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


-- spaced_learning.modules definition

-- Drop table

-- DROP TABLE spaced_learning.modules;

CREATE TABLE spaced_learning.modules (
	id uuid NOT NULL,
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	module_no int4 NOT NULL,
	title varchar(255) NOT NULL,
	word_count int4 NULL,
	book_id uuid NOT NULL,
	CONSTRAINT modules_module_no_check CHECK ((module_no >= 1)),
	CONSTRAINT modules_pkey PRIMARY KEY (id),
	CONSTRAINT modules_word_count_check CHECK ((word_count >= 0)),
	CONSTRAINT fkh6s7r2n5vtsmg4xjhao3818t FOREIGN KEY (book_id) REFERENCES spaced_learning.books(id)
);


-- spaced_learning.user_roles definition

-- Drop table

-- DROP TABLE spaced_learning.user_roles;

CREATE TABLE spaced_learning.user_roles (
	user_id uuid NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
	CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES spaced_learning.roles(id),
	CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id)
);


-- spaced_learning.module_progress definition

-- Drop table

-- DROP TABLE spaced_learning.module_progress;

CREATE TABLE spaced_learning.module_progress (
	id uuid NOT NULL,
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	cycles_studied varchar(30) NULL,
	first_learning_date date NULL,
	next_study_date date NULL,
	percent_complete numeric(5, 2) NULL,
	module_id uuid NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT module_progress_cycles_studied_check CHECK (((cycles_studied)::text = ANY ((ARRAY['FIRST_TIME'::character varying, 'FIRST_REVIEW'::character varying, 'SECOND_REVIEW'::character varying, 'THIRD_REVIEW'::character varying, 'MORE_THAN_THREE_REVIEWS'::character varying])::text[]))),
	CONSTRAINT module_progress_pkey PRIMARY KEY (id),
	CONSTRAINT fkiiw4sskvnx9ym1nixq197p0fo FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id),
	CONSTRAINT fkiwivm59wd0328gij7gayrr37 FOREIGN KEY (module_id) REFERENCES spaced_learning.modules(id)
);


-- spaced_learning.repetitions definition

-- Drop table

-- DROP TABLE spaced_learning.repetitions;

CREATE TABLE spaced_learning.repetitions (
	id uuid NOT NULL,
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	repetition_order varchar(20) NOT NULL,
	review_date date NULL,
	status varchar(50) NULL,
	module_progress_id uuid NOT NULL,
	CONSTRAINT repetitions_pkey PRIMARY KEY (id),
	CONSTRAINT repetitions_repetition_order_check CHECK (((repetition_order)::text = ANY ((ARRAY['FIRST_REPETITION'::character varying, 'SECOND_REPETITION'::character varying, 'THIRD_REPETITION'::character varying, 'FOURTH_REPETITION'::character varying, 'FIFTH_REPETITION'::character varying])::text[]))),
	CONSTRAINT repetitions_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'COMPLETED'::character varying, 'SKIPPED'::character varying])::text[]))),
	CONSTRAINT fk9lj2refs205nnsscajx9tywsk FOREIGN KEY (module_progress_id) REFERENCES spaced_learning.module_progress(id)
);
