CREATE TABLE spaced_learning.books (
    id uuid NOT NULL,                    -- Khóa chính
    "name" varchar(100) NOT NULL,        -- Tên sách là thông tin quan trọng
    book_no int4 NULL,                   -- Số thứ tự sách
    category varchar(50) NULL,           -- Danh mục
    difficulty_level varchar(20) NULL,   -- Mức độ khó
    status varchar(20) NULL,             -- Trạng thái
    description text NULL,               -- Mô tả chi tiết
    created_at timestamp(6) NULL,        -- Thời gian tạo
    updated_at timestamp(6) NULL,        -- Thời gian cập nhật
    deleted_at timestamp(6) NULL,        -- Thời gian xóa
    CONSTRAINT books_difficulty_level_check CHECK (((difficulty_level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'EXPERT'::character varying])::text[]))),
    CONSTRAINT books_pkey PRIMARY KEY (id),
    CONSTRAINT books_status_check CHECK (((status)::text = ANY ((ARRAY['PUBLISHED'::character varying, 'DRAFT'::character varying, 'ARCHIVED'::character varying])::text[])))
);

CREATE TABLE spaced_learning.roles (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, -- Khóa chính
    "name" varchar(50) NOT NULL,         -- Tên vai trò là thông tin chính
    description varchar(255) NULL,       -- Mô tả bổ sung
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);

CREATE TABLE spaced_learning.users (
    id uuid NOT NULL,                    -- Khóa chính
    email varchar(100) NOT NULL,         -- Email là định danh chính
    "name" varchar(100) NOT NULL,        -- Tên người dùng
    "password" varchar(120) NOT NULL,    -- Mật khẩu
    username varchar(50) NULL,           -- Tên đăng nhập
    status varchar(20) NULL,             -- Trạng thái
    last_active_date timestamp(6) NULL,  -- Lần hoạt động cuối
    created_at timestamp(6) NULL,        -- Thời gian tạo
    updated_at timestamp(6) NULL,        -- Thời gian cập nhật
    deleted_at timestamp(6) NULL,        -- Thời gian xóa
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

CREATE TABLE spaced_learning.modules (
    id uuid NOT NULL,                    -- Khóa chính
    book_id uuid NOT NULL,               -- Khóa ngoại liên kết với books
    title varchar(255) NOT NULL,         -- Tiêu đề module
    module_no int4 NOT NULL,             -- Số thứ tự module
    word_count int4 NULL,                -- Số từ
    created_at timestamp(6) NULL,        -- Thời gian tạo
    updated_at timestamp(6) NULL,        -- Thời gian cập nhật
    deleted_at timestamp(6) NULL,        -- Thời gian xóa
    CONSTRAINT modules_module_no_check CHECK ((module_no >= 1)),
    CONSTRAINT modules_pkey PRIMARY KEY (id),
    CONSTRAINT modules_word_count_check CHECK ((word_count >= 0)),
    CONSTRAINT fkh6s7r2n5vtsmg4xjhao3818t FOREIGN KEY (book_id) REFERENCES spaced_learning.books(id)
);

CREATE TABLE spaced_learning.user_roles (
    user_id uuid NOT NULL,               -- Khóa ngoại liên kết với users
    role_id int8 NOT NULL,               -- Khóa ngoại liên kết với roles
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES spaced_learning.roles(id),
    CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id)
);

CREATE TABLE spaced_learning.module_progress (
    id uuid NOT NULL,                    -- Khóa chính
    user_id uuid NOT NULL,               -- Khóa ngoại liên kết với users
    module_id uuid NOT NULL,             -- Khóa ngoại liên kết với modules
    percent_complete numeric(5, 2) NULL, -- Tiến độ hoàn thành
    cycles_studied varchar(30) NULL,     -- Chu kỳ học
    first_learning_date date NULL,       -- Ngày bắt đầu học
    next_study_date date NULL,           -- Ngày học tiếp theo
    created_at timestamp(6) NULL,        -- Thời gian tạo
    updated_at timestamp(6) NULL,        -- Thời gian cập nhật
    deleted_at timestamp(6) NULL,        -- Thời gian xóa
    CONSTRAINT module_progress_cycles_studied_check CHECK (((cycles_studied)::text = ANY ((ARRAY['FIRST_TIME'::character varying, 'FIRST_REVIEW'::character varying, 'SECOND_REVIEW'::character varying, 'THIRD_REVIEW'::character varying, 'MORE_THAN_THREE_REVIEWS'::character varying])::text[]))),
    CONSTRAINT module_progress_pkey PRIMARY KEY (id),
    CONSTRAINT fkiiw4sskvnx9ym1nixq197p0fo FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id),
    CONSTRAINT fkiwivm59wd0328gij7gayrr37 FOREIGN KEY (module_id) REFERENCES spaced_learning.modules(id)
);

CREATE TABLE spaced_learning.repetitions (
    id uuid NOT NULL,                    -- Khóa chính
    module_progress_id uuid NOT NULL,    -- Khóa ngoại liên kết với module_progress
    repetition_order varchar(20) NOT NULL, -- Thứ tự lặp lại
    status varchar(50) NULL,             -- Trạng thái
    review_date date NULL,               -- Ngày ôn tập
    created_at timestamp(6) NULL,        -- Thời gian tạo
    updated_at timestamp(6) NULL,        -- Thời gian cập nhật
    deleted_at timestamp(6) NULL,        -- Thời gian xóa
    CONSTRAINT repetitions_pkey PRIMARY KEY (id),
    CONSTRAINT repetitions_repetition_order_check CHECK (((repetition_order)::text = ANY ((ARRAY['FIRST_REPETITION'::character varying, 'SECOND_REPETITION'::character varying, 'THIRD_REPETITION'::character varying, 'FOURTH_REPETITION'::character varying, 'FIFTH_REPETITION'::character varying])::text[]))),
    CONSTRAINT repetitions_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'COMPLETED'::character varying, 'SKIPPED'::character varying])::text[]))),
    CONSTRAINT fk9lj2refs205nnsscajx9tywsk FOREIGN KEY (module_progress_id) REFERENCES spaced_learning.module_progress(id)
);
-- spaced_learning.user_statistics definition

-- Drop table

-- DROP TABLE spaced_learning.user_statistics;

CREATE TABLE spaced_learning.user_statistics (
	id uuid NOT NULL,
	user_id uuid NOT NULL,
	streak_days int4 NULL,
	streak_weeks int4 NULL,
	longest_streak_days int4 NULL,
	last_statistics_update timestamp(6) NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	CONSTRAINT uk14hay547dsmu33phkweirx73y UNIQUE (user_id),
	CONSTRAINT user_statistics_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_user_stats_user ON spaced_learning.user_statistics USING btree (user_id);


-- spaced_learning.user_statistics foreign keys

ALTER TABLE spaced_learning.user_statistics ADD CONSTRAINT fkn3hnvsmybu7g7ntrwpg563sao FOREIGN KEY (user_id) REFERENCES spaced_learning.users(id);
